from signals.providers.base import MarketDataProvider
from signals.providers.yfinance_provider import YFinanceDataProvider
from signals.providers.mock_provider import MockDataProvider
from signals.providers.realtime_provider import RealTimeMarketDataProvider
from signals.providers import get_data_provider

# Backward compatibility aliases
BrokerAPIProvider = RealTimeMarketDataProvider
LicensedMarketDataProvider = RealTimeMarketDataProvider
